DATA:
  DATASET: imagenet22K
MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window7_224_22k
  DROP_PATH_RATE: 0.1
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
TRAIN:
  EPOCHS: 500
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.05
#  BASE_LR: 1.25e-4 # 4096 batch-size adapter
#  BASE_LR: 9.25e-4 # DTD
#  BASE_LR: 5.25e-4 # Aircraft
  BASE_LR: 3.25e-4 # Aircraft
  WARMUP_LR: 1.25e-7
  MIN_LR: 1.25e-6